# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v2
    - name: debug
      run: ls
    - name: debug pwd
      run: pwd
    - name: apt update test
      run: apt update
