# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: [local-eduwer]
    container: gradle:6.7-jdk8
    steps:
    - uses: actions/checkout@v2
    - name: Unit Tests
      run: gradle clean test
    - name: Build JAR
      run: gradle clean bootJar -x test
    
