# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-application:
    runs-on: [local-eduwer]
    container: gradle:6.7-jdk8
    steps:
    - uses: actions/checkout@v2
    - name: Unit Tests
      run: gradle clean test
    - name: Build JAR
      run: gradle clean build -x test
    - name: debug
      run: ls
    - uses: actions/upload-artifact@v2
      with: 
        name: build-application
        path: build/libs/*.jar
  build-docker-image:
    runs-on: [local-eduwer]
    needs: build-application
    container: docker:latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build-application
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Create Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: eduwer/money-conversions-back:latest
    
